hmrc/trusts

app/uk/gov/hmrc/trusts/connector/DesConnector.scala
- updated to send correct auth token to des.
=> [TRUS-679] updated to fix authorization issue for des.

app/uk/gov/hmrc/trusts/models/Models.scala, test/uk/gov/hmrc/trusts/controllers/CheckTrustControllerSpec.scala, test/uk/gov/hmrc/trusts/controllers/TrustsControllerSpec.scala
Updated postcode regex to accept lowercase postcode.
=> updated postcoder reg ex to accept lowercase.

app/uk/gov/hmrc/trusts/config/AppConfig.scala, app/uk/gov/hmrc/trusts/connector/DesConnector.scala, app/uk/gov/hmrc/trusts/connector/TaxEnrolmentConnector.scala, app/uk/gov/hmrc/trusts/controllers/CheckTrustController.scala, app/uk/gov/hmrc/trusts/controllers/RegisterTrustController.scala, app/uk/gov/hmrc/trusts/controllers/TaxEnrolmentCallbackController.scala, app/uk/gov/hmrc/trusts/exceptions/Exceptions.scala, app/uk/gov/hmrc/trusts/models/RegistrationTrustResponse.scala, app/uk/gov/hmrc/trusts/models/SubscriptionIdResponse.scala, app/uk/gov/hmrc/trusts/models/TaxEnrolmentSubscription.scala, app/uk/gov/hmrc/trusts/models/TaxEnrolmentSuscriberResponse.scala, app/uk/gov/hmrc/trusts/services/AuthService.scala, app/uk/gov/hmrc/trusts/services/DesService.scala, app/uk/gov/hmrc/trusts/services/RosmPatternService.scala, app/uk/gov/hmrc/trusts/services/TaxEnrolmentsService.scala, app/uk/gov/hmrc/trusts/utils/Contstants.scala, conf/app.routes, conf/application.conf, test/uk/gov/hmrc/trusts/connectors/BaseConnectorSpec.scala, test/uk/gov/hmrc/trusts/connectors/BaseSpec.scala, test/uk/gov/hmrc/trusts/connectors/DesConnectorSpec.scala, test/uk/gov/hmrc/trusts/connectors/TaxEnrolmentConnectorSpec.scala, test/uk/gov/hmrc/trusts/controllers/CheckTrustControllerSpec.scala, test/uk/gov/hmrc/trusts/controllers/RegisterTrustControllerSpec.scala, test/uk/gov/hmrc/trusts/controllers/TaxEnrolmentCallbackControllerSpec.scala, test/uk/gov/hmrc/trusts/services/DesServiceSpec.scala, test/uk/gov/hmrc/trusts/services/RosmPatternServiceSpec.scala, test/uk/gov/hmrc/trusts/services/TaxEnrolmentsServiceSpec.scala
- get the subscription id from des.
- set the subscription to tax enrolment.
- callback url for tax enrolment to callback.
=> [TRUS-677] Tax enrolment for Orgnisation affinity group user.

app/uk/gov/hmrc/trusts/models/SchemaModels.scala, app/uk/gov/hmrc/trusts/services/ValidationService.scala, app/uk/gov/hmrc/trusts/utils/DomainValidator.scala, app/uk/gov/hmrc/trusts/utils/TypeOfTrust.scala, app/uk/gov/hmrc/trusts/utils/ValidationUtil.scala, test/resources/trust-business-validation-fail.json, test/resources/valid-trusts-org-trustees.json, test/resources/valid-trusts-registration-api.json, test/uk/gov/hmrc/trusts/controllers/RegisterTrustControllerSpec.scala, test/uk/gov/hmrc/trusts/services/ValidationServiceSpec.scala, test/uk/gov/hmrc/trusts/utils/DataExamples.scala, test/uk/gov/hmrc/trusts/utils/DomainValidatorSpec.scala, test/uk/gov/hmrc/trusts/utils/JsonRequests.scala
validation for 
- start date
- efrbs start date
=> [TRUS-866] Validation for trust details section

app/uk/gov/hmrc/trusts/utils/DomainValidator.scala, app/uk/gov/hmrc/trusts/utils/ValidationUtil.scala, test/resources/trust-without-large-ben-description.json, test/resources/trusts-dynamic.json, test/resources/valid-trusts-org-trustees.json, test/resources/valid-trusts-registration-api.json, test/uk/gov/hmrc/trusts/services/ValidationServiceSpec.scala, test/uk/gov/hmrc/trusts/utils/DataExamples.scala, test/uk/gov/hmrc/trusts/utils/DomainValidatorSpec.scala
- 1 beneficiary is required
- Company and Employment related beneficiary (large type) is limited to 5 descriptions 'description' is mandatory, the other 4 are optional
- Cannot have a duplicate NINO across individual beneficiaries
- Beneficiaries date of birth cannot be a future date
- Beneficiaries date of birth must be 1500/01/01 or after
- Beneficiaries Passport Expiration Date can be in the past
- Beneficiary Passport Number cannot have a duplicate in other beneficiary entities or ID card details
=> [TRUS-892] Validation and Business Validation - Beneficiaries

app/uk/gov/hmrc/trusts/models/SchemaModels.scala, app/uk/gov/hmrc/trusts/utils/AssetsDomainValidation.scala, app/uk/gov/hmrc/trusts/utils/DomainValidator.scala, conf/resources/schemas/trustsApiRegistrationSchema_3.2.0.json, test/resources/employment-related-trusts-1.json, test/resources/invalid-payload-trusts-registration.json, test/resources/trust-business-validation-fail.json, test/resources/trust-without-large-ben-description.json, test/resources/trusts-dynamic-1.json, test/resources/trusts-dynamic.json, test/resources/valid-trusts-org-trustees.json, test/resources/valid-trusts-registration-api.json, test/uk/gov/hmrc/trusts/services/ValidationServiceSpec.scala, test/uk/gov/hmrc/trusts/utils/AssetsDomainValidationSpec.scala, test/uk/gov/hmrc/trusts/utils/DataExamples.scala
* There must be 1 Asset 
* Maximum of 1 monetary asset, other assets allow 10 of each.
* All value fields are up to 12 digits
Rules for Property or Land Asset: 
* The first monetary amount field (valueFull) must be equal to or more than the monetary amount in the second monetary field.
=> [TRUS-893]  Validation and Business Validation - Assets

app/uk/gov/hmrc/trusts/models/EstatesSchemaModels.scala, app/uk/gov/hmrc/trusts/services/ValidationService.scala, app/uk/gov/hmrc/trusts/utils/EstateDomainValidator.scala, build.sbt, conf/resources/schemas/estatesRegistrationSchema_3.2.0.json, test/resources/estate-registration-dynamic-01.json, test/resources/estate-registration-org-dynamic-01.json, test/resources/valid-estate-registration-04.json, test/uk/gov/hmrc/trusts/services/ValidationServiceSpec.scala, test/uk/gov/hmrc/trusts/utils/EstateDataExamples.scala, test/uk/gov/hmrc/trusts/utils/EstateDomainValidatorSpec.scala
*Personal Representative - Individual*
* Personal Representative date of birth cannot be a future date
* Personal Representative date of birth must be 1500/01/01 or after
* Personal Representative passport expiration date can be in the past
* Address is mandatory 
*Personal Representative - Organisation*
* Personal Representative Organisation UTR cannot be the same as the SAUTR of the Trust in the MatchData in schema
* Address is mandatory
=> [TRUS-994] Validation for estate registration

app/uk/gov/hmrc/trusts/config/AppConfig.scala, app/uk/gov/hmrc/trusts/models/EstatesSchemaModels.scala, app/uk/gov/hmrc/trusts/models/SchemaModels.scala, conf/resources/schemas/estates-api-schema-5.0.json, conf/resources/schemas/trusts-api-schema-5.0.json, conf/resources/schemas/trustsApiRegistrationSchema_3.2.0.json, test/resources/valid-trusts-deed-of-variation-01.json, test/resources/valid-trusts-registration-api.json, test/uk/gov/hmrc/trusts/services/ValidationServiceSpec.scala
- lead trustee identification type.
- natural person identification.
=> [TRUS-1084] Updating schema as per des 5.0 schema

app/uk/gov/hmrc/trusts/models/SchemaModels.scala, app/uk/gov/hmrc/trusts/utils/AssetsDomainValidation.scala, app/uk/gov/hmrc/trusts/utils/ValidationUtil.scala, conf/resources/schemas/trusts-api-schema-5.0.json, test/resources/trusts-without-trustees-identification.json, test/resources/valid-trusts-org-trustees.json, test/resources/valid-trusts-registration-api.json, test/uk/gov/hmrc/trusts/services/ValidationServiceSpec.scala, test/uk/gov/hmrc/trusts/utils/DataExamples.scala
updated to make identification mandatory for beneficiary charity, tru…
=> api changes as per frontend

app/uk/gov/hmrc/trusts/models/SchemaModels.scala, test/resources/valid-trusts-org-trustees.json, test/uk/gov/hmrc/trusts/services/ValidationServiceSpec.scala, test/uk/gov/hmrc/trusts/utils/DataExamples.scala
This aligns with Validation matrix v20
=>  Fix model for trustee individual to not longer require a date of birth

app/uk/gov/hmrc/trusts/controllers/RegisterEstateController.scala, app/uk/gov/hmrc/trusts/controllers/RegisterTrustController.scala
removing validation errors from log.
=> removing validation errors from log.

app/uk/gov/hmrc/trusts/models/SchemaModels.scala, app/uk/gov/hmrc/trusts/utils/DeedOfVariation.scala, app/uk/gov/hmrc/trusts/utils/DomainValidator.scala, app/uk/gov/hmrc/trusts/utils/SettlorDomainValidation.scala, app/uk/gov/hmrc/trusts/utils/ValidationUtil.scala, test/resources/deed-of-variation-in-addition-to-a-will-trust-both-settlors.json, test/resources/deed-of-variation-in-addition-to-a-will-trust-no-deceased.json, test/resources/deed-of-variation-in-addition-to-a-will-trust-no-living-settlor.json, test/resources/deed-of-variation-replaced-the-will-deceased.json, test/resources/deed-of-variation-replaced-the-will-no-living.json, test/uk/gov/hmrc/trusts/services/DesServiceSpec.scala, test/uk/gov/hmrc/trusts/utils/DataExamples.scala, test/uk/gov/hmrc/trusts/utils/DomainValidatorSpec.scala, test/uk/gov/hmrc/trusts/utils/SettlorDomainValidatorSpec.scala
- Refactoring the domain validation for deed of variation trusts to
explicitly state which settlors allows depending on how the variation
was created.
=> TRUS-1337 Refactoring domain validation

app/uk/gov/hmrc/trusts/connector/DesConnector.scala
- Incorrect auth header was being provided
=> Creating a new Header Carrier

app/uk/gov/hmrc/trusts/models/get_trust_or_estate/get_trust/GetTrustSchemaModels.scala, test/resources/valid-get-trust-response.json, test/uk/gov/hmrc/trusts/connectors/DesConnectorSpec.scala, test/uk/gov/hmrc/trusts/services/DesServiceSpec.scala
[TRUS-1944] - Change format of Lead Trustee in backend
=> [TRUS-1944] - Change format of Lead Trustee in backend

it/uk/gov/hmrc/repositories/AddTrusteeSpec.scala, test/resources/trusts-etmp-received-no-trustees.json, test/uk/gov/hmrc/trusts/transformers/DeclarationTransformerSpec.scala
code was already in place.  Have added a test to document the case
=> Prune trustees

app/uk/gov/hmrc/trusts/transformers/JsonOperations.scala, app/uk/gov/hmrc/trusts/transformers/RemoveBeneficiariesTransform.scala, app/uk/gov/hmrc/trusts/transformers/RemoveTrusteeTransform.scala, test/resources/trusts-etmp-get-trust-remove-trustee-ind.json, test/resources/trusts-etmp-received-empty-trustees.json, test/uk/gov/hmrc/trusts/transformers/RemoveBeneficiariesTransformSpec.scala
Convert some custom handling to use JsonOperations.
=> Prune empty array when entity is removed. 

app/uk/gov/hmrc/trusts/controllers/TrustVariationsController.scala, app/uk/gov/hmrc/trusts/models/TrustRegistrationModels.scala, app/uk/gov/hmrc/trusts/transformers/DeclarationTransformer.scala, test/resources/trusts-etmp-sent-end-date.json, test/uk/gov/hmrc/trusts/controllers/TrustVariationsControllerSpec.scala, test/uk/gov/hmrc/trusts/services/VariationServiceSpec.scala, test/uk/gov/hmrc/trusts/transformers/DeclarationTransformerSpec.scala
…ndDate in declaration transforms if it exists.
=> TRUS-1963 : Adding end date when closing trust

app/uk/gov/hmrc/trusts/controllers/SubmissionDraftController.scala, test/uk/gov/hmrc/trusts/controllers/SubmissionDraftControllerSpec.scala
register-trust-details-frontend
=> Adding trust start date at new path under

app/controllers/TrustDetailsTransformationController.scala, app/services/TrustDetailsTransformationService.scala, app/transformers/DeltaTransform.scala, app/transformers/trustDetails/SetUKRelationTransform.scala, conf/trusts.routes, test/controllers/TrustDetailsTransformationControllerSpec.scala, test/services/TrustDetailsTransformationServiceSpec.scala, test/transformers/DeltaTransformSpec.scala
- Add in missing controllers specs and service spec
=> Add endpoint for trust uk relation

app/services/BeneficiaryTransformationService.scala, app/services/OtherIndividualTransformationService.scala, app/services/ProtectorTransformationService.scala, app/services/SettlorTransformationService.scala, app/services/TransformationService.scala, app/services/TrusteeTransformationService.scala, app/services/VariationService.scala, app/transformers/DeclarationTransformer.scala, conf/logback.xml, it/uk/gov/hmrc/transformations/SetExpressSpec.scala, it/uk/gov/hmrc/transformations/SetPropertySpec.scala, it/uk/gov/hmrc/transformations/SetRecordedSpec.scala, it/uk/gov/hmrc/transformations/SetRelationSpec.scala, it/uk/gov/hmrc/transformations/SetResidentSpec.scala, it/uk/gov/hmrc/transformations/SetTaxableSpec.scala, test/controllers/BeneficiaryTransformationControllerSpec.scala, test/controllers/GetTrustControllerSpec.scala, test/controllers/OtherIndividualTransformationControllerSpec.scala, test/controllers/ProtectorTransformationControllerSpec.scala, test/controllers/SettlorTransformationControllerSpec.scala, test/controllers/TrusteeTransformationControllerSpec.scala, test/resources/logback-test.xml, test/services/BeneficiaryTransformationServiceSpec.scala, test/services/OtherIndividualTransformationServiceSpec.scala, test/services/ProtectorTransformationServiceSpec.scala, test/services/SettlorTransformationServiceSpec.scala, test/services/TrustDetailsTransformationServiceSpec.scala, test/services/TrusteeTransformationServiceSpec.scala, test/services/VariationServiceSpec.scala
PR covers:
1. Adding integration tests for new transform APIs
2. Fixing a bug where not implemented was returned rather than failing the Reads[T]
3. Adding header carrier to services for logging purposes
=> TRUS-3420 Integration tests and fix for Reads[T] rather than return a NotImplemented Exception

app/connector/DesConnector.scala
- Removed from stub and no longer expected
=> No longer send old correlationId header

app/connector/DesConnector.scala
This can be merged once the trusts service is pointed to IF for Register, Display and Variation
=> Removing guard for its0 in QA environment

conf/resources/schemas/5MLD/trusts-api-registration-schema-1.3.0.json
=> Revert "No longer mandating CR10 fields"

conf/trusts.protectors.routes, conf/trusts.routes, conf/trusts.settlors.routes
…DO to remove routes from trusts.routes at a later date.
=> Moved remaining settlors and protectors routes

app/connector/TrustsConnector.scala, app/controllers/RegisterTrustController.scala, app/models/TrustRegistrationModels.scala, app/models/auditing/TrustRegistrationSubmissionAuditEvent.scala, app/models/registration/RegistrationResponse.scala, app/services/AuditService.scala, app/services/Default5mldDataService.scala, app/services/TrustsService.scala, test/services/FakeAuditService.scala
- Splitting error channel from trn channel in response
- Removing unneeded http reeads to determine between the two
- Split the audit chanel into two
=> TRUS-3781 Submission date for 5mld

app/controllers/SubmissionDraftController.scala, conf/register.routes, test/controllers/SubmissionDraftControllerSpec.scala
=> Revert "DDCE-2463 Remove unused endpoint"

app/config/AppConfig.scala, app/controllers/TrustDetailsSubmissionDraftController.scala, app/models/TrustRegistrationModels.scala, app/utils/DomainValidator.scala, conf/register.routes, conf/resources/schemas/5MLD/trusts-api-registration-schema-1.4.2.json, test/resources/valid-trusts-registration-api-5mld.json, test/services/ValidationServiceSpec.scala, test/utils/DataExamples.scala, test/utils/DomainValidatorSpec.scala
_This is a rebase of Richy's original PR_
Update trusts-api-registration-schema with schedule3aExempt
Add endpoint to retrieve isExpress
Add domain validation for schedule3aExempt
=> [DDCE-3155] - Schedule 3a Exempt
